---
- hosts: hiren
  become: yes
  become_flags: "-E"
  become_user: prism
  gather_facts: no

  tasks:
    - name: Building main binary
      command: go build .
      args:
        chdir: /home/prism/newsarchive/Hiren-NewsArchive-SSR/
      environment:
        PATH: "/home/prism/go/bin"
    - name: Building sitemap binary
      command: go build sitemap/main.go
      args:
          chdir: /home/prism/newsarchive/Hiren-NewsArchive-SSR/
      environment:
          PATH: "/home/prism/go/bin"