---
- hosts: hiren
  become: yes
  become_flags: "-E"
  become_user: prism
  gather_facts: no

  tasks:
    - name: Running git pull
      git:
        repo: git@github.com:pyprism/uCPingGraph.git
        dest: /home/prism/newsarchive/Hiren-NewsArchive-SSR/
        update: yes
        version: master